version: '3'
services:
  web:
    build: .
    command: ./entrypoint.sh
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - db
    hostname: web
    networks:
      static-network:
        ipv4_address: 172.20.0.6
    restart: unless-stopped
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_DB=lading
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=uZDCsacaxCsdcSDaw123c231A
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      static-network:
        ipv4_address: 172.20.0.7
    restart: unless-stopped

volumes:
  pgdata:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24