# Generated by Django 5.1.4 on 2024-12-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='message',
        ),
    ]
