# Generated by Django 5.1.4 on 2024-12-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_customers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(choices=[('Yangi', 'yangi'), ('Qabul qilingan', 'qabul qilingan'), ('Rad etilgan', 'rad etilgan')], default='Yangi', max_length=100),
        ),
    ]
