# Generated by Django 5.1.4 on 2024-12-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_customers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/announcements/'),
        ),
    ]
